# .github/workflows/build-and-deploy.yml
name: Build and Deploy Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build job
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '18'
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # Runs a set of commands to build
      - name: Build
        run: npm run build --prod
      # sotre the artifact