name: Build and Deploy Frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build --prod

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: page
          path: build
          if-no-files-found: error

  deploy:
    name: Deploy to Backend
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v2
        with:
          repository: gousehackathon/node-backend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: backend-repo

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: page
          path: ./build

      - name: Remove Old Build Files
        run: rm -rf backend-repo/path/to/build/*

      - name: Copy New Build Files
        run: cp -R ./build/* backend-repo/path/to/build/

      - name: Commit and Push Changes
        run: |
          cd backend-repo
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Deploy frontend build'
          git push origin master
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
